### ISSUE TITLE
How to get MCM working on Mod Organizer 2.

### ISSUE THREAD

**Issue by stonefisher0** [Neanka/MCM_0.1_AS3#1]
The trouble with Mod Organizer 2 is that it stops mods generating new files. This is what is stopping settings being saved once people get the mods recognized by MCM.

Step 1: 
Move the MCM folder from ModOrg 2\Fallout 4\Mods\<MCM based mod>
to
Fallout 4\Data

Step 2:
Copy the name of the mods ESP file e.g. MCM_Demo.esp or QuickTrade.esp
Go to Fallout 4\Data\MCM and generate a folder labeled "Settings" if needed.
Inside the Settings folder right click and make a new txt file.
Rename file to the name of the ESP file and change file extension to "ini" e.g. MCM_Demo.ini or QuickTrade.ini

That's it. The mod will now appear in the MCM menu and settings will be persistent.

Also of note, a file called "Keybinds.json" may appear inside some folders in your Overwrite folder in Mod Organizer 2. This is where the keybindings are stored. You can leave it there or move it to the appropriate location inside Fallout 4\Data\MCM\Settings.

Suggestion to mod authors.
Please add an appropriately named ini file inside the Settings folder for us MO2 users.

**Comment by Scrivener07** [comment]
So if I understand correctly, a mod author should include dummy versions of all possible files that may be generated at runtime. This will prevent MO from losing the file yea? I dont not use MO so Im not familiar with its nuances.

**Comment by stonefisher0** [comment]
Pretty much.  I believe only the ini file is needed.

When hunting for a solution the file Keybinds.json was already in the existing mod folders inside the MCM\config folder. MO2 could thus generate a file with the same name in a different location using the ovewrite folder. MO2 is designed not to overwrite existing files and put replacement files in the overwrite folder which goes lower down in the load order.

MO2 is awesome, just a shame it was never finished. I have never actually used NMM. Before this I used Mod Organizer 1 and before that it was FOMM. I have always found the individual folders for each mod and the clear and easy indicators of what overwrites what just so handy.

**Comment by reg2k** [comment]
The latest release of MO2 should not require any additional configuration for MCM-enabled mods to work with it.
