### ISSUE TITLE
[FEATURE REQUEST] More Conditional Display Options

### ISSUE THREAD

**Issue by nephatrine** [Neanka/MCM_0.1_AS3#11]
I'd like a way to conditionally display controls based on whether another plugin is loaded. Alternatively doing so based on something like a GlobalVariable and leaving it to the mod to detect the other plugins and set the variables themselves is fine too. There just isn't a good option I can see for mods that have optional functionality that depends on other mods aside from having a completely separate MCM menu entry for it that detects the other plugin, but that is clunky and creates a lot of clutter in the MCM menu.

**Comment by shadowslasher410** [comment]
You can already do that. See https://github.com/Neanka/MCM_0.1_AS3/wiki/Display-Conditions for more information. If you already know about that and just want to add more, you can add as many group controls and group conditions as you want.
