### ISSUE TITLE
mcm not showing in pause menu

### ISSUE THREAD

**Issue by luiszagan** [Neanka/MCM_0.1_AS3#16]
the mcm just doesn't show up in my pause scream, plus mods messaging that the mcm most be reinstalled

**Comment by AWARHERO** [comment]
I'm using F4SE 0.6.5 rel 12 and FO4 1.10.64.0
So far the MCM option in the Game menu never shows up but mods that requires MCM do not give me any messages ...

I've tried this with no mods installed and only MCM mod... Still the same results.
I've then installed an additional mod (Wait anywhere) and still the MCM menu is not showing.

**Comment by Gymiq** [comment]
same problem here, can anyone please help ? :(

**Comment by Neanka** [comment]
try to install it manually and check if loose files disabled

**Comment by Gymiq** [comment]
I tried manual and mod manager download, what do you mean by loose files disabled ? Sorry I'm pretty slow, I just started modding.

**Comment by Neanka** [comment]
google `f4 enable loose files`

**Comment by Gymiq** [comment]
Oh okay, I actually already added the following script in Fallout4Custom.ini if that's what you mean

[Archive] 
bInvalidateOlderFiles=1
sResourceDataDirsFinal=

**Comment by Neanka** [comment]
and u running game with f4se_loader.exe and mcm doesn't show in pause menu?

**Comment by Gymiq** [comment]
OMG my bad, I thought f4se_loader was an extra file to enable the mod, didn't realize it was actually a launcher until you told me.. Thank you ! XD
