### ISSUE TITLE
Cast {value}

### ISSUE THREAD

**Issue by kinggath** [Neanka/MCM_0.1_AS3#24]
EDIT: Further research - I can only seem to get a float {value} to work. Are we unable to cast {value}? As in {i}{value}?

As far as I can tell, I can only seem to get GlobalValues to work with CallFunction - but now that I know that I can't cast the {value}, it might be that my previous attempts were just incorrect... Will update other ticket once I learn more.

**Comment by kinggath** [comment]
Now that I figured out what I was doing wrong with the properties - I know what I have to do!

**Comment by Neanka** [comment]
@kinggath try this file. use `"params": ["{i}-1", "{i}{value}", "{i}-1"]`
[MCM.zip](https://github.com/Neanka/MCM_0.1_AS3/files/2019625/MCM.zip)

**Comment by kinggath** [comment]
Works great - thank you!

Is this something you can push to the live version soon? I'd like to release MCM support with next weekend's Sim Settlements patch.

**Comment by Neanka** [comment]
i can upload it on nexus after couple of days. or may be @reg2k can do it earlier

**Comment by reg2k** [comment]
I can push to Nexus Wednesday evening if you haven't already by then
