### ISSUE TITLE
no menu

### ISSUE THREAD

**Issue by Krugej** [Neanka/MCM_0.1_AS3#26]
hi, 
 I installed the new mcm update and I have no menure at all in the pause screen. looks the same as the vanilla game. any ideas as to why ?  was install with NMM

**Comment by Krugej** [comment]
Menu*

**Comment by Neanka** [comment]
Check:
1. loose files enabled
2. all files from archive installed properly
3. run game with f4se loader

**Comment by Krugej** [comment]
I did all the above and still it doesn't show up. though i'm not sure how to enable loose files

**Comment by Krugej** [comment]
found out how to enable loose files but still no luck

**Comment by Krugej** [comment]
I tried reinstalling everything and no menu. any other ideas ?

**Comment by Neanka** [comment]
Give me screenshots of main menu, pause menu, f4se.log and mcm.log from documents/my games/f4/f4se folder.

**Comment by Krugej** [comment]
[f4se.log](https://github.com/Neanka/MCM_0.1_AS3/files/2055726/f4se.log)
there is no MCM log

**Comment by Krugej** [comment]
I screenshoted and made a file of the mcm install and the enable coding on my comp if you want to see them

**Comment by Krugej** [comment]
![f04_data_f4se_folder](https://user-images.githubusercontent.com/39739215/40753463-844ee9b4-6431-11e8-82af-5ce890ac87d2.jpg)
![f4se screenshot](https://user-images.githubusercontent.com/39739215/40753468-85f7e27a-6431-11e8-8cc4-6f7ca76f1e72.jpg)
![fo4 interface](https://user-images.githubusercontent.com/39739215/40753469-87e75138-6431-11e8-9f90-ed95f87507bd.jpg)
![fo4 perfs](https://user-images.githubusercontent.com/39739215/40753472-89eca3b6-6431-11e8-913c-8fdde3a33e86.jpg)
![fo4 source file](https://user-images.githubusercontent.com/39739215/40753476-8c01cdfc-6431-11e8-9b9f-2b9b4f40df29.jpg)
![fo4_data_folder_mcm](https://user-images.githubusercontent.com/39739215/40753480-8e490b84-6431-11e8-8b4f-ecb1c59e6402.jpg)
![fo4_scripts](https://user-images.githubusercontent.com/39739215/40753482-904f42ea-6431-11e8-83f3-5160f52068a4.jpg)
![fo4custom](https://user-images.githubusercontent.com/39739215/40753484-95b99848-6431-11e8-952d-d8ea357fb132.jpg)

**Comment by Krugej** [comment]
![nmm with mcm installed](https://user-images.githubusercontent.com/39739215/40753872-6948a6da-6433-11e8-819d-4a85ab311c0e.jpg)
![pause menu](https://user-images.githubusercontent.com/39739215/40753874-6aef6a0a-6433-11e8-89d7-93281ddbf8f3.jpg)
![main menu fo4](https://user-images.githubusercontent.com/39739215/40753897-8d4dcbaa-6433-11e8-9829-6b9280cf6c8a.jpg)

**Comment by Krugej** [comment]
ok install pics as well as main menu and pause menu are all here as well as NMM showing the mcm install

**Comment by Neanka** [comment]
![image](https://user-images.githubusercontent.com/16521679/40760463-5c38d8d4-64b0-11e8-96b6-2594af0815c8.png)
looks like u have some troubles with f4se. what in f4se_loader.log?

**Comment by Krugej** [comment]
here is the log. I did reinstall f4se on the 30th

**Comment by Neanka** [comment]
looks like f4se_loader.log not attached

**Comment by Krugej** [comment]
I think i got it this time :)

**Comment by Krugej** [comment]
did you get my attachments?

**Comment by Neanka** [comment]
Nope. Probably u can't attach via emailОтправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail01.06.2018, 03:34, "Krugej" <notifications@github.com>:did you get my attachments?

**Comment by Krugej** [comment]
[f4se_steam_loader.log](https://github.com/Neanka/MCM_0.1_AS3/files/2061373/f4se_steam_loader.log)

**Comment by Neanka** [comment]
![image](https://user-images.githubusercontent.com/16521679/40856983-21d061fa-65f3-11e8-86f4-311531c13a28.png)

feel free to figure out why f4se doesnt work here https://discord.gg/cJPzPXB

**Comment by Krugej** [comment]
I have another question. I redownloaded MCM manually and when I tried to
install it I didn't see the MCM.swf after unzipping it. was that not
included in the zip file ?

**Comment by Neanka** [comment]
are you kidding us? 
![image](https://user-images.githubusercontent.com/16521679/40874857-8fa644ce-668e-11e8-9ed9-4e4af8fa3894.png)

**Comment by Krugej** [comment]
I didn't mean to offend or blame anyone,  but this is what I get when I
unzipped the file

**Comment by Jadex611** [comment]
ya I'm also having troubles even though nothing seems out of place it just won't load the menu

**Comment by Krugej** [comment]
I think there is a hidden menu for fo4 that we have to delete. I vaguely
remember doing that for skyrim because of the same issue

**Comment by Neanka** [comment]
Guy with the same issue with not working f4se found a solution 
![image](https://user-images.githubusercontent.com/16521679/41326627-4379c6d6-6ed9-11e8-8ddb-9bb8c4f7e9bd.png)

**Comment by slushieman234** [comment]
i have the same issue, running it as admin doesn't work. I can't directly open fo4 as admin but I can open steam as admin.
