### ISSUE TITLE
Hotkeys with Params Not Working

### ISSUE THREAD

**Issue by kinggath** [Neanka/MCM_0.1_AS3#27]
I've been trying to set up hotkeys with parameters and they don't seem to work. Here's a sample definition I'm using - maybe I've just got a mistake?

{
	  "id": "SS_ASAMVisionToggle_Homeless",
	  "desc": "Sim Settlements: Toggle Find Homeless.",
	  "action": {
		"type": "CallFunction",
		"form": "SimSettlements.esm|2E0E", //SimParent
                "function": "MCMToggleASAMVision",
		"params": ["{i}1"]
	  }
	}

I've tried this with and without the typecast to see if that was the problem, doesn't seem to be. Hotkeys with functions sans parameters work great.

**Comment by Neanka** [comment]
hotkeys doesnt support type casts at all and use just field type from json parser. so ur "params": ["1"] is String but not int
Solution: `"params": [1]`
