### ISSUE TITLE
Cannot set RunConsoleCommand hotkey

### ISSUE THREAD

**Issue by gkaniouris** [Neanka/MCM_0.1_AS3#29]
I am trying to create a hotkey for [West Tek Tactical Optics](https://www.nexusmods.com/fallout4/mods/12220?tab=description).

I am using ModOrganizer v2.1.3 and I have created a separate mod that contains the following directory structure:
- MCM
-- Config
--- West Tek Tactical Optics
---- config.json
---- keybinds.json

The contents of the two files are:
config.json:
```json
{
    "modName":"WTTO",
    "displayName":"West Tek Tactical Optics",
    "minMcmVersion":1,
    "pluginRequirements":[
        "WestTekTacticalOptics.esp"
    ],
    "content":[
        {
            "id": "WTTO_Toggle_Mode",
            "text": "Toggle Mode",
            "type": "hotkey",
            "help": "Toggles the headset's mode"
        }
    ]
}
```

keybinds.json
```
{
    "modName": "WTTO",         
    "keybinds": [
        {
            "id": "WTTO_Toggle_Mode",
            "desc": "Toggles the headset's mode",
            "action": {
                "type": "RunConsoleCommand",
                "command": "CallQuestFunction WestTek_GoggleControlQuest GoggleToggle"
            }
        }
    ]
}
```

The problem I am facing is that when I try to save the hotkey the value is not saved. The menus appear correctly but when I press on the key I want to assign the value is not saved. For example, if I want to assign the key N to that hotkey, I click on the "None" text in MCM, the prompts (TAB: clear etc.) change accordingly, then I press "N" on my keyboard. At that point the character "N" will appear in MCM for a second but then "None" will return. Also, the hotkey option does not appear in the Hotkey Manager.

Can you help me understand why this is happening? Do I have to save the hotkey value somewhere, by using the info in "Setting Types, Storage and Persistence"?

Note that the WTTO creator does not officially support MCM. So I am guessing that their .esp has no idea about MCM. I am just trying to save the console command they mention [here](https://www.nexusmods.com/fallout4/articles/426) to create the hotkey.

**Comment by gkaniouris** [comment]
Also, I just tried the MCM Demo and the hotkeys where save correctly

**Comment by Neanka** [comment]
folder name must match `modName`
![image](https://user-images.githubusercontent.com/16521679/41573207-fc4f6106-7394-11e8-8cc3-027a21f30647.png)

**Comment by gkaniouris** [comment]
Oh ok. Thank you.
