### ISSUE TITLE
MCM Causing Laggy game

### ISSUE THREAD

**Issue by fitzgery** [Neanka/MCM_0.1_AS3#3]
*******EDIT*******
It wasn't your mod that caused it, just got a lucky save game load it seems right after I uninstalled it. Sorry for the misunderstanding

**NOT FURTHER APPLICABLE**
Hey there, so I downloaded your MCM mod today (9/12/17) with NMM, ran LOOT and what not and when I loaded my game it was horribly laggy, about a 5 second response time if it responded. I uninstalled the MCM mod and the issue has gone away. So idk if I did something wrong or what but im just confused why it caused my game to be so laggy

**Comment by Neanka** [comment]
👌
