### ISSUE TITLE
MCM.dll stops f4se.exe from working?

### ISSUE THREAD

**Issue by meowingtonz** [Neanka/MCM_0.1_AS3#30]
fallout ver. 1.10.089
mcm ver. 1.27
f4se ver. 0.6.9

MCM.dll file when installed in correct file path c:/programfiles(x86)/steam/steamapps/common/Fallout4/Data/F4SE/plugins/....

when i try to execute f4se.exe via desktop shortcut, it loads (cmd) prompt, and then shuts down.

I've tried troubleshooting, fresh install of all mods, removing all mods, reinstalling all mods from scratch, if i remove MCM.DLL; all other mods work and f4se.exe loads into the game with near full functionality (i.e. the tweak settings and hotkey binding of mod's like bullet time and nightvision goggles cant be applied).

have i missed something glaringly obvious? i just cant seem to figure this one out. No one else seems to be encountering this from my googling. 

i guess my question is, is this a clash between f4se and MCM, or what next steps can i try to fix it. 

![mcm dll stopping f4se exe from executing](https://user-images.githubusercontent.com/40570255/41854572-72154746-7888-11e8-829a-2a0fac686300.png)

![f4se exe screenshot](https://user-images.githubusercontent.com/40570255/41854834-108b1d1a-7889-11e8-9cdf-cd931edf6fb9.png)

**Comment by Neanka** [comment]
show me mcm.log and f4se.log, also try to use 1.26 version or disable another plugins except mcm and look how it will going

**Comment by meowingtonz** [comment]
[f4se.log](https://github.com/Neanka/MCM_0.1_AS3/files/2144453/f4se.log)
i think this is the one that you wanted?
as for the MCM.logs i couldn't upload directly so ive screen shotted. 

UPDATE:with the most recent update, (0.98) and new f4se (0.6.10) it now says that (see screenshot), which I think is progress as before, it would shut down immediately, will await update to MCM before testing further as i think this will fix it. 

![mcm disabled](https://user-images.githubusercontent.com/40570255/42023939-faa92b40-7ab8-11e8-8c3e-5254826469e1.png)

![mcm 1 26](https://user-images.githubusercontent.com/40570255/42023771-93b6b24a-7ab8-11e8-9949-ff9cb51f0f32.png)
![mcm 127](https://user-images.githubusercontent.com/40570255/42023772-93d56460-7ab8-11e8-8471-07be441bbf1a.png)

**Comment by meowingtonz** [comment]
Fantastic news! with the 1.28 update it now works together again! i still have no idea what was wrong with it other than a clash between sim settlement and it messing  MCM up. :S anyway at least it works now. 

thanks gang!
