### ISSUE TITLE
MCM not compatible with Fallout 4 v1.10.98.0

### ISSUE THREAD

**Issue by michaelstuder** [Neanka/MCM_0.1_AS3#31]
- New release of Fallout 4 (Steam)
- Updated version of F4SE
- Need an update to MCM per:

![image](https://user-images.githubusercontent.com/2319603/42035357-b806266a-7ab0-11e8-9b8d-2377abfb48c6.png)

**Comment by Neanka** [comment]
may be u can wait mod update at least 1 day instead of being captain obvious?

**Comment by Scrivener07** [comment]
Im sure he was just trying to be helpful. I filed more or less the same issue on one of my own.
