### ISSUE TITLE
Fallout 4 Mod config menu your game version: v1.10.98.0 expected version:v1.10.89.0 mod configuration menu will be disabled

### ISSUE THREAD

**Issue by Mavi2684** [Neanka/MCM_0.1_AS3#32]
When I go to open the script extender I get this message 
"your game version: v1.10.98.0 expected version:v1.10.89.0 mod configuration menu will be disabled"
I need this so I can fix my pippad mod or try and figure out why my pippad is disappearing. Please someone help this is getting on my nerves

**Comment by Neanka** [comment]
Update mod for latest version
