### ISSUE TITLE
Issue with current version 1.30 not had in 1.29

### ISSUE THREAD

**Issue by Nickd91** [Neanka/MCM_0.1_AS3#35]
After updating MCM and F4SE to the curent versions, I have had an issue with settings in the MCM taking effect.

Bullet Time's settings save visually in the MCM, however they do not change the mods global values properly. Game Configuration Menu values seem to update properly, however its force weather change function fails and does nothing. I am not certain if these mods require an update to work properly with the current versions of FO4, F4SE, and MCM.

I have checked permissions on pretty much every folder and even tried running everything as an admin, including making sure nothing was read-only.

I cannot think of anything else to try short of rolling back to the previous versions of FO4, F4SE, and MCM.

**Comment by Scrivener07** [comment]
Same issue for me involving function calls. I had the simple configuration that was working before the update.

```json
{
	"text": "Add Item, H3 ODST Helmet",
	"type": "button",
	"help": "Adds the item to your inventory.",
	"action":
	{
		"type": "CallFunction",
		"form": "ODST.esp|FA8",
		"function": "Armor_H3_ODST_Helmet"
	}
},
```

**Comment by reg2k** [comment]
Can you also try this DLL to see if it solves the issue?
[mcm.zip](https://github.com/Neanka/MCM_0.1_AS3/files/2341868/mcm.zip)

**Comment by reg2k** [comment]
Can you try this SWF and see if it solves the issue?
[MCM.zip](https://github.com/Neanka/MCM_0.1_AS3/files/2341879/MCM.zip)

**Comment by H3X1C** [comment]
@reg2k The dll you uploaded resolved the issue on my end

**Comment by H3X1C** [comment]
Reverted the dll to the latest release, used the SWF file you post above. Callfunction is working as intended, the MCM demo message box works as well as my mods call functions.

**Comment by reg2k** [comment]
Thanks for verifying. v1.30 was packaged with an outdated SWF. I've now uploaded v1.31 to the Nexus.

**Comment by Scrivener07** [comment]
@reg2k The hotfix you uploaded is working for me too. This may be a separate issue but does the `CallFunction` action support a script name? Below the armor button does not work but the helmet does, I guess because of the `scriptName`. It seems to work for properties.

```
{
	"text": "Add Item, H3 ODST Armor",
	"type": "button",
	"help": "Adds the item to your inventory.",
	"action":
	{
		"type": "CallFunction",
		"form": "ODST.esp|FA8",
		"function": "Armor_H3_ODST",
		"scriptName": "ODST:Special:Cheats"
	}
},
{
	"text": "Add Item, H3 ODST Helmet",
	"type": "button",
	"help": "Adds the item to your inventory.",
	"action":
	{
		"type": "CallFunction",
		"form": "ODST.esp|FA8",
		"function": "Armor_H3_ODST_Helmet"
	}
},
```

**Comment by reg2k** [comment]
`scriptName` for CallFunction should work - do the logs say anything?

**Comment by Scrivener07** [comment]
Yes, the logs say the following after two button presses on the control.
```
MCM v1.30
MCM query
MCM load
---
sig: 40 53 55 56 57 41 54 48 81 EC ? ? ? ? 8B 15 ? ? ? ?
effective address: 0000000140F5B380
RVA: 0x0125B380
---
---
sig: 40 55 56 41 57 48 8D 6C 24 ?
effective address: 0000000141E0F69C
RVA: 0x0210F69C
---
---
sig: 48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 48 83 EC 20 48 8B F9 48 8B CA 41 0F B6 F1
effective address: 0000000142418920
RVA: 0x02718920
---
Sigscan elapsed: 181 ms.
ModSettingStore initializing.
Number of mod setting files: 1
Registered 26 mod settings in 18 ms.
Registered Papyrus native functions.
Registered for input events.
Registered for input events.
WARNING: ODST.esp|FA8 cannot be resolved to a Papyrus script object.
WARNING: ODST.esp|FA8 cannot be resolved to a Papyrus script object.
```

**Comment by reg2k** [comment]
@Scrivener07 You misspelled the script name in your config - your script is `ODST:Special:Cheat` but you have the following in your config: `"scriptName": "ODST:Special:Cheats"`.

**Comment by Scrivener07** [comment]
And there it was right in front of me the whole time. Thanks for the help reg2k.
