### ISSUE TITLE
Ammo still have weight after disabling it in patch 1.10.26

### ISSUE THREAD

**Issue by Paraxdq** [Neanka/MCM_0.1_AS3#4]
Hello, 
today I updated fallout 4 from 1.10.20 to 1.10.26 and accordingly f4se and other mods. 
I had to change the settings for the no ammo / stimpack weight inside mcm after updating but it still doesn't work for me, console works fine tho.

**Comment by Neanka** [comment]
try to reinstall both USM and MCM

**Comment by Paraxdq** [comment]
Oh yeah im dumb, I thought the menu of USM was from MCM but that are different mods, so this is definitly the wrong report section for it, sorry :D
