### ISSUE TITLE
MCM (mod name).esp is missing

### ISSUE THREAD

**Issue by Hemal2** [Neanka/MCM_0.1_AS3#45]
I have a couple mods not working with the MCM I have the mods properly installed and had them installed in the past, but I uninstall them for one reason or another. With them uninstalled, it's understandable that it would say the .esp is missing, but when I reinstall the mod, it gives me the same warning. I have tried clean installs of MCM and the mods I want (particularly survival options), but those didn't work.

**Comment by Hemal2** [comment]
Update: Any new mods I install will not work with MCM either and give me the missing .esp error

**Comment by Scrivener07** [comment]
Open the game to the main menu without loading any game saves. Open the dev console and type `coc RedrocketExt`. Once you arrive at the redrocket try the MCM with your mods. If it does not work at this point then something with your installation is messed up. If it does work then something is wrong with your specific game save.

Uninstallation is NOT supported by the game even though there might be cases where it does work.
Do not take uninstallation of mods lightly.

**Comment by Hemal2** [comment]
I've not actually started a game yet, I've just been creating new games until I can get the mods working to actually play. It isn't the one save, as I've been trying multiple. Nonetheless, I tried what you said and I still have the missing plugins warning. When you say installation, do you mean my load order? I've reinstalled MCM twice, and the mods I want working as well.

Some more information, some mods work because I have not uninstalled them yet. I have the immersive HUD mod, and that works fine, but mods like VAFS Redux and Survival options don't.

And when you say uninstallation is not supported by the game, do you mean just on a save-by-save basis? or the game entirely?

Edit: I have just realized that one mod I uninstalled, Advanced Needs 2, is no longer showing up on the MCM, unlike the other mods (survival options and VAFS), this one doesn't get me a warning when it has been uninstalled.

**Comment by Hemal2** [comment]
I have found a fix. Go to your fallout 4 folder, head to data/mcm/config, and delete the folders for the corresponding mods that are broken. Reinstall the mods after that. It should fix then
