### ISSUE TITLE
MCM occassionally doesn't load (Fallout 4)

### ISSUE THREAD

**Issue by annalinneajohansson** [Neanka/MCM_0.1_AS3#5]
Apparently random MCM doesn't load at all when I start the game. Haven't been able to debug it since it seems to happen regardless of if I've made any changes or not; restarting the game entirely _sometimes_ help, sometimes not.

Have replace the desktop shortcut with the one for f4se_loader.exe so I'm always starting with F4SE. Have 242 plugins active at the moment, will include the load order. When MCM _does_ load it works just fine.

GameMode=Fallout4

Fallout4.esm=1
DLCRobot.esm=1
DLCWorkshop01.esm=1
DLCCoast.esm=1
DLCWorkshop02.esm=1
DLCWorkshop03.esm=1
DLCNukaWorld.esm=1
ArmorKeywords.esm=1
HUDFramework.esm=1
Eisenwolfs Legacy.esm=1
VideoMaster.esm=1
CROSS_CosmeticFramework.esm=1
Robot Home Defence.esm=1
SimSettlements.esm=1
AD_SimSettlements_BuidingPlans_TAGS1.esm=1
My_Minutemen.esp=1
Crafting Workbench.esp=1
Crafting Workbenches - Removed Crafting Experience.esp=1
Crafting Workbenches - Junk Items.esp=1
Crafting Workbenches - Faction and Quest Requirements.esp=1
Crafting Workbenches - Automatron DLC.esp=1
CBBE.esp=1
Armorsmith Extended.esp=1
Armorsmith All DLCs Patch.esp=1
SettlementMenuManager.esp=1
RPHSettlement.esp=1
StartMeUp.esp=1
StartMeUpNukaWorldPatch.esp=1
EFF.esp=1
Companion_BloodRose.esp=1
NWS_Barbara.esp=1
BeastWhisperer.esp=1
betterstores.esp=1
bs-farharborexpansion.esp=1
RHDaddon.esp=1
RHDE Scrap Robots.esp=1
QuickTrade.esp=1
AutoEat.esp=1
TurretSpotLight-mod-v01.esp=1
ConstructionLight_ExtraBright_Shadows_Wireless.esp=1
SkjAlert_All_DLC.esp=1
NoLollygagging.esp=1
Hobo-Scavenger.esp=1
No Junk Comments.esp=1
RenCloseThatDoorMod.esp=1
Repaired Roofs.esp=1
Running with Corpses.esp=1
Power Conduits and Pylons - Increased Radius x3.esp=1
You Talk Too Much.esp=1
A Variety of Containers.esp=1
FlirtyCommonwealth.esp=1
Laurent's Robot Skins.esp=1
RobotMilitaryPaint.esp=1
Abduction.esp=1
AbductionNamedNPCs.esp=1
More detailed perk description dlc version.esp=1
mso_sms.esp=1
CompanionAccuracy.esp=1
RobotAccuracy.esp=1
ProvisionerOverhaul.esp=1
soepack_vanillamenufixer.esp=1
SurvivalOptions.esp=1
CheatTerminal.esp=1
Pip-Boy Flashlight.esp=1
OutfitSwitcher.esp=1
Journey.esp=1
FO4 NPCs Travel.esp=1
IcebreakerCDO-Settlements.esp=1
Killable Children.esp=1
Raider Children.esp=1
AA Lots More Settlers and Enemies.esp=1
Marmo1233 - Immersive Settlers.esp=1
Strong Back - Survival - DLCCoast.esp=1
PipBoyShadows.esp=1
Vivid Weathers - FO4.esp=1
Vivid Weathers - FO4 - Far Harbor.esp=1
Vivid Weathers - FO4 - Spring.esp=1
Vivid Weathers - Natural Bright.esp=1
Vivid Weathers - Nuka World.esp=1
Vivid Fallout - All in One - Best Choice.esp=1
DynamicInteriorFogRemoval.esp=1
FAR.esp=1
EMIB.esp=1
ASEFarHarbor.esp=1
clothingoverhaul.esp=1
clothingoverhaulsp_xb1_pc.esp=1
moddablerobotsettlers.esp=1
Goodfellow's Diamond City Defences.esp=1
Goodfellow's Goodneighbor Defences.esp=1
Settler_Radio.esp=1
SpecialVideos.esp=1
StarlightDriveInVideos.esp=1
GoodOldCartoons.esp=1
GoodOldCartoonsBonus.esp=1
Burly Q set1.esp=0
Burly Q set2.esp=0
Burly Q set3.esp=0
Red Rocket Settlements.esp=1
MysticPinesRetirementSettlement.esp=1
Settler Sandbox Overhaul.esp=1
UniversityPointSettlementSPE.esp=1
KenmoreStation.esp=1
citydead.esp=1
The Metro.esp=1
settlemods_fiddlersgreen.esp=1
Crimsomrider's Taffington Boathouse.esp=1
clothinghair_merge.esp=1
KSHairdos.esp=0
ZellaHairDyeV2.esp=0
Survivalist.esp=0
AzarPonytailHairstyles.esp=0
EoW_MakeupColors.esp=0
DX Vault Girl Shorts.esp=0
Eli_ApachiiDreadlocks.esp=0
DX Commonwealth Shorts.esp=0
Eli_Armour_Compendium.esp=1
Eli_Apocalypse Attire.esp=1
Sporty Underwear.esp=1
Mercenary.esp=1
ScavengedMercGear.esp=1
WastelandFashion.esp=1
Wasteland Fashion  Armorsmith Patch.esp=1
WastelandFashion - Leveled Lists.esp=1
WastelandFashionAccessories.esp=1
K9TacticalHarness.esp=1
Survivalist GoBags-Chem Station.esp=1
TroublemakerOutfit.esp=1
Friffy_Holstered Weapons.esp=1
ProvisionerBackPack.esp=1
HoodieOutfit.esp=1
CROSS_Uni_Headset.esp=1
CROSS_Uni_Headset_LeveledLists.esp=1
Eli Armor Compendium AE Patch.esp=1
Femshepping_WastelandPinup.esp=1
WestTekTacticalOptics.esp=1
WestTekTacticalOptics-AWKCR.esp=1
AnS Wearable Backpacks and Pouches.esp=1
AnS Wearable Backpacks and Pouches - Power Armor Carry Capacity.esp=1
AnS Wearable Backpacks and Pouches - AWKCR Power Armor.esp=1
Rebel Backpacks.esp=1
AdnamaOutfit_ALLinONE.esp=1
CROSS_Cybernetics.esp=1
HelmetToggle.esp=1
Kor_Highlight.esp=1
QuickSwap.esp=1
VATSMove.esp=1
WoodenPrefabsExtended.esp=1
HelmetHide.esp=1
salvagebeacons.esp=1
Less Annoying Well Rested and Lovers Embrace.esp=1
Modern Firearms.esp=1
CorvalhoWidowShotgun.esp=1
GrenadeLauncherStandalone.esp=1
Evan_Modular Kitchen.esp=1
Cozy Beds.esp=1
RaiderQuadBike.esp=1
Eli_Crafting Shiz 9000.esp=1
PaintingDisabler.esp=1
BetterJunkFences.esp=1
ExpandedSettlementBuildings.esp=1
dinoshelf.esp=1
CR_OuthouseCollection.esp=1
ButcherMeatRack.esp=1
CompactCrafting.esp=1
Craftable Adhesives.esp=1
CraftableAnimationMarkers.esp=1
CREAtiveClutter.esp=1
deFENCES.esp=1
AkaInvisibleFurniture.esp=1
EvilViking13_MinutemenMorale.esp=1
RealTroughs.esp=1
Settlement_Markers.esp=1
TidySettlers.esp=1
Wall Oil Lamps.esp=1
Weapon Rack Extended.esp=1
WindowBoards.esp=1
dinoshelf_extra_ammo.esp=1
More Scavenging Stations.esp=1
CWSS Redux.esp=1
functionalobjects_vanilla_SMM.esp=1
Housekeeping.esp=1
Northland Diggers New.esp=1
Prisoner Shackles.esp=1
PCDugWedges.esp=1
EAMR.esp=1
RRTV_RobotModelKits.esp=1
TabsMissingFix_DLC_WW_CW.esp=1
MarcyLongDialogueEdits.esp=1
cartman1975_warehouse.esp=1
woodysWastelandStuff.esp=1
Crimsomrider's Unique Furniture.esp=1
Thematic and Practical.esp=1
Thematic and Practical - DLC.esp=1
SnapBeds.esp=1
TurretStands.esp=1
WWP - PC.esp=1
SimSettlements_XPAC_IndustrialRevolution.esp=1
IndustrialCity_Sim_Settlements_Addon.esp=1
home_improvement_all.esp=1
TrailerParkDreams.esp=1
Shadows_for_Sim_Settlements.esp=1
ClassicShacks.esp=1
ohSIM_Sim_Settlements_Scrappers_Addon.esp=1
JibsResidentialAddOnPack.esp=1
SimSettlements_AddOnPack_Utilities_JtBryant.esp=1
SimHomestead.esp=1
WVSimSAddon.esp=1
ruined_simsettlement_addonpack.esp=1
SS Addon Hunter-Gather.esp=1
PCDugSIMAddon.esp=1
SimSettlements_AddOnPack_Defences_Brae.esp=1
AGOMBz.esp=1
AllSetsExtended.esp=1
MJC_Sim_Settlements_Addon.esp=1
Altairp's Animal Farm.esp=1
B84sThemedResidentials.esp=1
AnotherBrickInTheWall.esp=1
AGOMBz_CP_ASE_ASEFH.esp=1
Orphans.esp=1
orphans AE Patch.esp=1
Realistic Death Physics - ALL DLC.esp=1
ValdacilsItemSorting-MERGED.esp=1
more realistic headshots-MERGED.esp=1
LooksMenu.esp=1
Hide Quests From Pipboy.esp=1
more realistic headshots.esp=0
more realistic headshots - automatron.esp=0
more realistic headshots - nuka world.esp=0
more realistic headshots - far harbor.esp=0
ValdacilsItemSorting-00-ValsPicks-DLCVersion-VanillaWeight.esp=0
ValdacilsItemSorting-Aid.esp=0
ValdacilsItemSorting-Ammo.esp=0
ValdacilsItemSorting-ArmorBySlot.esp=0
ValdacilsItemSorting-CosmeticsByClass.esp=0
ValdacilsItemSorting-ExplosivesSortBottom.esp=0
ValdacilsItemSorting-JunkBetter+DEF_INV.esp=0
ValdacilsItemSorting-MiscWeightless.esp=0
ValdacilsItemSorting-Mods.esp=0
ValdacilsItemSorting-NotJunk.esp=0
ValdacilsItemSorting-Perks.esp=0
ValdacilsItemSorting-ZY-DLCAutomatron.esp=0
ValdacilsItemSorting-ZY-DLCContraptions.esp=0
ValdacilsItemSorting-ZY-DLCFarHarbor.esp=0
ValdacilsItemSorting-ZY-DLCNukaWorld.esp=0
ValdacilsItemSorting-ZY-DLCVaultTec.esp=0
SettlementAttacksBeyond.esp=0
Conquest.esp=0
Cleaner AIO Environment Indoor and Outdoor (No Fog).esp=1
Scrapper Corpse Highlighting.esp=0
Scrapper Corpse Highlighting DLC Patch.esp=0
Worthless Clothing.esp=0
BeastMaster_ExoticCreaturesPatch.esp=0
Z_Horizon.esp=1
rebel camo pack.esp=1
the rebel flannels.esp=1
Z_StartMeUp_HorizonPatch.esp=1
Z_Horizon_WeaponPack01.esp=1
MM-Horizon-Patch.esp=1
EAC-Horizon-Patch.esp=1
Z_Horizon_Mercenary.esp=1
Z_Horizon_Patch_SimSettlements.esp=1
Z_Horizon_DLC_All.esp=1
Z_Horizon_Diff_Veteran.esp=1
Z_Horizon_DEFUI.esp=1
Z_Horizon_Mode_Scavenger.esp=1
Z_Horizon_Timescale.esp=1
Z_Horizon_Patch_ArmorsmithExtended.esp=1
Z_BlurRemoval.esp=1
Z_Horizon_Patch_ArmorsmithExtendedDLC.esp=1
Z_CameraAddon.esp=1
EAC-MM-Patch.esp=1
HAIA.esp=1
ImmersiveScrapping_SeasonPass.esp=1
Scrap Everything - Ultimate Edition.esp=1
Z_Horizon_Patch_ScrapEverything.esp=1
ScrapDeadThings.esp=1
OCDecorator.esp=1
OCDecoratorDLC.esp=1
OCDispenser.esp=0

**Comment by annalinneajohansson** [comment]
Could this be an issue with F4SE rather than MCM?

**Comment by Neanka** [comment]
can u show f4se.log when mcm not loaded?

**Comment by annalinneajohansson** [comment]
It seems as if nothing is being written to the log when MCM isn't loaded, and looking more carefully it does seem that *any* F4SE dependent plugins also doesn't work whenever this happens. So this do seem to be a F4SE issue rater than MCM, right?

This is my log when MCM *is* loaded. (When not, nothing at all is written to the log.)
[f4se - mcm loaded.log](https://github.com/Neanka/MCM_0.1_AS3/files/1381503/f4se.-.mcm.loaded.log)

**Comment by annalinneajohansson** [comment]
As suspected - this isn't a MCM issue at all! Finally realized what was causing it; I was starting the game via f4se_loader.exe without first starting up Steam and that apparently caused F4SE to not load correctly.

Sorry for taking up your time! :) Thank you for a great plugin also.
