### ISSUE TITLE
MCM Not detecting Mod .esp file

### ISSUE THREAD

**Issue by ConnorVex** [Neanka/MCM_0.1_AS3#69]
Greetings, I am trying to use the MCM with the [Bullet Time - Slow Time](https://www.nexusmods.com/fallout4/mods/9325?tab=description). However whenever I enter the game and try to edit the config, the MCM is telling me the .esp file is missing, however the .esp file is in the data directory! Help please!

![image](https://github.com/Neanka/MCM_0.1_AS3/assets/79610595/6764d93a-7668-4429-b246-be8b4d38d6e1)

![image](https://github.com/Neanka/MCM_0.1_AS3/assets/79610595/87a2f6e8-1405-4513-b414-4763fecff783)

**Comment by Neanka** [comment]
make sure eps is enabled

**Comment by ConnorVex** [comment]
> make sure eps is enabled

How can I do that?

**Comment by Neanka** [comment]
from mod manager or from in-game mods menu

**Comment by ConnorVex** [comment]
![image](https://github.com/Neanka/MCM_0.1_AS3/assets/79610595/4eef2d3f-2ad7-4184-af96-6e5fcc334b66)

![image](https://github.com/Neanka/MCM_0.1_AS3/assets/79610595/842cce21-ab0c-4cbb-a0d9-e905ca571bc0)

I have enabled it in the Fallout 4 Mod Manager, and its appearing in my game's mod list
Still spitting out that same error of the esp file missing

**Comment by ConnorVex** [comment]
Update:
So I wounded up fiddling with this and I was able to get it to work:
For those that have my same issue, be sure to use this mod manager to get it working:
https://www.nexusmods.com/skyrimspecialedition/mods/6194

Thank you for helping out!
