### ISSUE TITLE
Not Translating Correctly

### ISSUE THREAD

**Issue by ShqRNa** [Neanka/MCM_0.1_AS3#7]
In the pause menu, 'MOD CONFIG' shows up as $MOD_CONFIG, 'MCM Settings' $MCM_SETTINGS, 'MCM Hotkey Manager' $MCM_HOTKEY_MANAGER. Aside from this, MCM appears to perform as it should.

I found just one other person with the same issue and there wasn't much help there:

> "Hey am using 1.9.4 Game Version same goes for F4SE and MCM but i see only on the menu $MOD_CONFIG and it's not usable.. anyidea what did i miss?"

**Details on my setup:** 

MCM version 1.20, Fallout 4 version 1.10.26, F4SE build 0.6.0.

Game is launched with F4SE using a fresh save, all MCM and F4SE files are accounted for, language used is English.

I've tried deactivating all plugins and reinstalling MCM and F4SE.

**Fallout4Custom.ini:**

> [Archive]
> sResourceDataDirsFinal= 
> bInvalidateOlderFiles=1

**Plugins:**

> *Unofficial Fallout 4 Patch.esp
> *HUDFramework.esm
> *XDI.esm // dialogue menu
> *SimSettlements.esm
> *console.esp // enables console commands for survival mode
> *SettlementMenuManager.esp
> *Immersive HUD.esp
> *SimSettlements_XPAC_IndustrialRevolution.esp
> *Pilgrim.esp // enb-weather-lighting-audio
> *Altyn Assault Helmet.esp // clothing
> *Metro Gas Masks.esp // clothing
> *zgcshadowscarf.esp // clothing

**MCM_en.txt:**

> $MOD_CONFIG	MOD CONFIG
> $MCM_HOTKEY_MANAGER	Hotkey Manager
> $MCM_KEYBIND_REPLACE	Replace Keybind
> $MCM_KEYBIND_BIND_ANYWAY	Bind Anyway
> $MCM_KEYBIND_IN_USE_MOD_1	This key is in use by the following mod:
> $MCM_KEYBIND_IN_USE_MOD_2	for the following action:
> $MCM_KEYBIND_IN_USE_GAME_1	Warning: this key is in use for the following game action:
> $MCM_KEYBIND_IN_USE_GAME_2	You may choose to bind the key anyway, but doing so will result in multiple actions when the key is pressed.
> $MCM_MISSING_PLUGINS	Missing plugins:
> $MCM_WRONG_VERSION	Wrong MCM version:
> $MCM_REQUIRED	required:
> $MCM_NO_HOTKEYS	There are no registered hotkeys.
> $MCM_CLEAR_HOTKEY	CLEAR
> 
> $MCM_SCALEX	SCALE X
> $MCM_SCALEY	SCALE Y
> $MCM_OPACITY	OPACITY
> $MCM_CONFIRM_CHANGES	Confirm changes?
> $MCM_SETTINGS	MCM Settings
> $MCM_MENU_POSITION	MCM position in the main menu
> $MCM_MENU_LOAD_ERROR	An error was encountered while loading this menu.
> 
> $MCM_CLEAR	CLEAR
> $MCM_MENU_MODS_ORDER	Menu order

**Comment by Neanka** [comment]
is trouble still here?

**Comment by reg2k** [comment]
Closed due to inactivity. Possible duplicate of #12.
