### ISSUE TITLE
The 2024-04-25 Fallout 4 update (1.10.980 and later) Broke MCM

### ISSUE THREAD

**Issue by kurtish** [Neanka/MCM_0.1_AS3#76]
Hi,

In case you were not aware the new 2024-04-25 Fallout 4 update (1.10.980) is no longer working with MCM

Not sure if it is the hooks to the old F4SE or the changes introduced to Fallout itself `2024-04-25 Fallout 4 update (1.10.980 and later)` that caused MCM to no longer function.

F4SE has released a new version Version 0.6.23 => Version 0.7.1 in case it is connected.

Thanks for your time

**Comment by Neanka** [comment]
believe me we are aware of the updates and are working on them even if you think we are inactive
although we should probably give more information to the public so they don't worry and generate bug reports.

**Comment by kurtish** [comment]
Thanks, again for the fast response :)

Keep up the great work, it is appreciated :)
