### ISSUE TITLE
Plugins Missing?

### ISSUE THREAD

**Issue by CPR1556** [Neanka/MCM_0.1_AS3#79]
The MCM plugins are completely missing. I have reinstalled both the 1.39 and 1.40 BETA versions of mcm (alongside updating F4SE, the game, and relevant mods) multiple times both manually and through Vortex, and each time the plugin file for the MCM is simply not there. I have verified this in both the actual game and through Vortex. I've even manually gone through the files for the MCM download and I see nothing missing when comparing it to the Nexus file contents. I've searched through dozens of forum posts and appear to be the only person to document this problem. I am at a complete loss as to what the issue could be and any potential advice would be appreciated.

**Comment by BeFranke** [comment]
Hey, I am having the exact same issue, did you ever manage to fix it?

**Comment by Neanka** [comment]
> Hey, I am having the exact same issue, did you ever manage to fix it?

MCM have no "plugin" file. it loads with f4se
