### ISSUE TITLE
MCM needs updating for new version v1.10.40.0

### ISSUE THREAD

**Issue by odmonk** [Neanka/MCM_0.1_AS3#8]
Currently MCM expects version v1.10.26.0 so just exits with the message that Mod Configuration Menu will be disabled.

**Comment by ConnorMcReynolds** [comment]
Needs updated for PC game version 1.10.40.0, my game won't even launch anymore, even after disabling MCM. Can't figure out which mods I have installed are relying on MCM. 
Waiting for MCM to be updated <3

**Comment by retsofd** [comment]
Just seconding this request for PC 1.10.40 support..  Thanks for all your efforts.

**Comment by reg2k** [comment]
MCM is updated for v1.10.40 (and v1.10.50).
