### ISSUE TITLE
MCM freezes my game after I opened it [FIXED]

### ISSUE THREAD

**Issue by Tea2Be** [Neanka/MCM_0.1_AS3#80]

**Comment by Tea2Be** [comment]
Update:
I found the problem that of the SCOURGE Mod making this issue with MCM.
It's most likely due to the SCOURGE mod using the newest version of Fallout 4, while I downgraded mine back to the last update before the Next-Gen Update.

**Comment by OsloTimbuktu** [comment]
Could you share how you fixed this issue? I'm experiencing a similar issue where MCM freezes my game after opening it.
