### ISSUE TITLE
MCM not working (game version 1.10.984.00) 

### ISSUE THREAD

**Issue by GamerEmpire2** [Neanka/MCM_0.1_AS3#82]
First off:

> Have the Steam ver of Fallout 4

> Mod Organizer

> I am aware it only works in-game

> my F4SE in main menu says: v(F4SE 0.7.2) 1.10.984.00

Info: 

I have tried everything I know to fix it and it still does not work in-game I have the latest MCM and F4SE in my game and I had have 3 mods installed F4SE, MCM, and a mod that uses F4SE and MCM

**Comment by Xariss00** [comment]
Which version of MCM do you have installed?

**Comment by GamerEmpire2** [comment]
i have download that with the "download to vortex" but it goes to my mod organizer
![image_2024-07-26_053519934](https://github.com/user-attachments/assets/753d42df-1cee-4203-acde-5f477172261d)

**Comment by Xariss00** [comment]
[MCM on Nexus Mods](https://www.nexusmods.com/fallout4/mods/21497?tab=files)

Uninstall your current version (1.39) of MCM.
Follow the above link to MCM on Nexus.
Scroll down to the second file that says, "For Fallout 4 game version 1.10.984 (next-gen update 2)."
Install correct version of MCM (1.40 BETA 2).

**Comment by GamerEmpire2** [comment]
it works thanks
